[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd server && npm start"
buildCommand = "cd client && npm install && npm run build && cd ../server && npm install && npm run build"

[env]
NODE_ENV = "production"
