-- Tabela de Subscriptions para integração com Cakto
-- Esta tabela armazena informações sobre assinaturas e pagamentos

-- Criar tabela de subscriptions
CREATE TABLE IF NOT EXISTS subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  customer_id VARCHAR(255) NOT NULL,
  plan VARCHAR(50) NOT NULL DEFAULT 'premium',
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  subscription_id VARCHAR(255),
  purchase_id VARCHAR(255),
  amount DECIMAL(10,2),
  currency VARCHAR(3) DEFAULT 'BRL',
  payment_method VARCHAR(50),
  interval VARCHAR(20) DEFAULT 'monthly',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  cancelled_at TIMESTAMP WITH TIME ZONE,
  expires_at TIMESTAMP WITH TIME ZONE
);

-- Criar índices para performance
CREATE INDEX IF NOT EXISTS idx_subscriptions_email ON subscriptions(email);
CREATE INDEX IF NOT EXISTS idx_subscriptions_customer_id ON subscriptions(customer_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON subscriptions(status);
CREATE INDEX IF NOT EXISTS idx_subscriptions_subscription_id ON subscriptions(subscription_id);

-- Adicionar coluna subscription_tier na tabela profiles se não existir
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'profiles' AND column_name = 'subscription_tier'
  ) THEN
    ALTER TABLE profiles ADD COLUMN subscription_tier VARCHAR(20) DEFAULT 'free';
  END IF;
END $$;

-- Atualizar timestamp automaticamente
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Criar trigger para atualizar updated_at
CREATE TRIGGER update_subscriptions_updated_at 
  BEFORE UPDATE ON subscriptions 
  FOR EACH ROW 
  EXECUTE FUNCTION update_updated_at_column();

-- Política de segurança (RLS) - permitir inserções via webhook
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;

-- Política para permitir inserções (webhook do Cakto)
CREATE POLICY "Allow webhook insertions" ON subscriptions
  FOR INSERT WITH CHECK (true);

-- Política para permitir atualizações (webhook do Cakto)
CREATE POLICY "Allow webhook updates" ON subscriptions
  FOR UPDATE USING (true);

-- Política para permitir leituras para usuários autenticados
CREATE POLICY "Allow authenticated reads" ON subscriptions
  FOR SELECT USING (auth.role() = 'authenticated');

-- Política para permitir que usuários vejam suas próprias subscriptions
CREATE POLICY "Allow users to see own subscriptions" ON subscriptions
  FOR SELECT USING (auth.email() = email);

-- Inserir dados de exemplo (opcional)
INSERT INTO subscriptions (email, customer_id, plan, status, amount, currency, interval) VALUES
('admin@crmpmg.com', 'cus_test_001', 'premium', 'active', 99.90, 'BRL', 'monthly'),
('joao.silva@exemplo.com', 'cus_test_002', 'premium', 'active', 99.90, 'BRL', 'monthly')
ON CONFLICT (customer_id) DO NOTHING;

-- Criar view para subscriptions ativas
CREATE OR REPLACE VIEW active_subscriptions AS
SELECT 
  id,
  email,
  customer_id,
  plan,
  status,
  amount,
  currency,
  interval,
  created_at,
  expires_at
FROM subscriptions 
WHERE status = 'active';

-- Criar função para verificar se usuário é premium
CREATE OR REPLACE FUNCTION is_premium(user_email TEXT)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM subscriptions 
    WHERE email = user_email 
    AND status = 'active' 
    AND (expires_at IS NULL OR expires_at > NOW())
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Criar função para obtier tier do usuário
CREATE OR REPLACE FUNCTION get_user_tier(user_email TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN COALESCE(
    (
      SELECT plan FROM subscriptions 
      WHERE email = user_email 
      AND status = 'active' 
      AND (expires_at IS NULL OR expires_at > NOW())
      LIMIT 1
    ), 
    'free'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Comentários para documentação
COMMENT ON TABLE subscriptions IS 'Tabela de assinaturas e pagamentos do CRM PMG - Integração com Cakto';
COMMENT ON COLUMN subscriptions.email IS 'Email do cliente';
COMMENT ON COLUMN subscriptions.customer_id IS 'ID do cliente no Cakto';
COMMENT ON COLUMN subscriptions.plan IS 'Plano da assinatura (free, premium, enterprise)';
COMMENT ON COLUMN subscriptions.status IS 'Status da assinatura (active, cancelled, expired)';
COMMENT ON COLUMN subscriptions.subscription_id IS 'ID da assinatura no Cakto';
COMMENT ON COLUMN subscriptions.purchase_id IS 'ID da compra no Cakto';
COMMENT ON COLUMN subscriptions.amount IS 'Valor da assinatura';
COMMENT ON COLUMN subscriptions.currency IS 'Moeda (BRL, USD, etc)';
COMMENT ON COLUMN subscriptions.payment_method IS 'Método de pagamento';
COMMENT ON COLUMN subscriptions.interval IS 'Intervalo de cobrança (monthly, yearly)';
COMMENT ON COLUMN subscriptions.created_at IS 'Data de criação';
COMMENT ON COLUMN subscriptions.updated_at IS 'Data da última atualização';
COMMENT ON COLUMN subscriptions.cancelled_at IS 'Data do cancelamento';
COMMENT ON COLUMN subscriptions.expires_at IS 'Data de expiração';

-- Criar função para webhook logging (opcional)
CREATE OR REPLACE TABLE IF NOT EXISTS webhook_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  webhook_type VARCHAR(50) NOT NULL,
  event_type VARCHAR(50) NOT NULL,
  payload JSONB NOT NULL,
  processed BOOLEAN DEFAULT FALSE,
  error_message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_webhook_logs_type ON webhook_logs(webhook_type);
CREATE INDEX IF NOT EXISTS idx_webhook_logs_processed ON webhook_logs(processed);
